version: "3.8"
services:
  node:
    build: .
    container_name: personal-portfolio
    hostname: personal-portfolio
    working_dir: /app
    ports:
      - "3000:80"
networks:
  default:
    external:
      name: app_network